name: trivy-send-mail

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  MAIL_PASSWD: ${{ secrets.MAIL_PASSWD }}
  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}

jobs:
  build:
    name: trivy-check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['python']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t newf:v1 .
        docker image tag newf:v1 mansi1811/newf:v1

    - name: Set up Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
        trivy -v

    - name: Scan Docker Image for Vulnerabilities with Trivy
      run: |
        trivy image --severity=HIGH,CRITICAL newf:v1
          
    - name: Convert Trivy Results to SARIF
      run: |
        trivy image --severity=HIGH,CRITICAL -f sarif newf:v1 > trivy-results.sarif
      shell: bash
      if: always()

    - name: Upload SARIF Report
      uses: actions/upload-artifact@v2
      with:
        name: trivy-results
        path: trivy-results.sarif
      if: always()
        
    - name: Push Docker Image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push mansi1811/newf:v1
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      shell: bash

    - name: Checkout repository
      uses: actions/checkout@v2
      if: always()

    - name: Download SARIF Report
      uses: actions/download-artifact@v2
      with:
        name: trivy-results
        path: trivy-results
      if: always()

    - name: Send SARIF Report Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWd}}
        to: mansi.s@sigmoidanalytics.com
        from: Mansi Singh
        subject: SARIF Report for trivy scanning
        body: Please find the trivy report attached.
        attachments: trivy-results/trivy-results.sarif
      if: always()
