name: Pre-Merge Checks

on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["Pylint", "gitleaks", "CodeQL"]
    types:
      - completed

jobs:
  build:
    name: pre-merge-check
    runs-on: ubuntu-latest
    strategy:
  #    fail-fast: true
      matrix:
        language: ['python']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Build Docker Image
        run: |
          docker build -t new:v1 .
          docker image tag new:v1 mansi1811/new:v1

      - name: Set up Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy -v

      - name: Scan Docker Image for Vulnerabilities with Trivy
        run: |
          trivy image --severity=HIGH,CRITICAL --exit-code 1 new:v1

      - name: Convert Trivy Results to SARIF
        run: |
          trivy image --severity=HIGH,CRITICAL -f sarif new:v1 \
           > trivy-results.sarif
        shell: bash
        if: always()

      - name: Upload SARIF Report
        uses: actions/upload-artifact@v2
        with:
          name: trivy-results
          path: trivy-results.sarif
        if: always()

      - name: Push Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
          docker push mansi1811/new:v1
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        shell: bash
